### ISSUE TITLE
Can you please port this to Tensorflow.js?

### ISSUE THREAD

**Issue by tejaswigowda** [starkgate/Distraction-aware-Shadow-Detection#1]

**Comment by starkgate** [comment]
Do you realise how much work that is? No, do it yourself.

**Comment by tejaswigowda** [comment]
> Do you realise how much work that is? No, do it yourself.

Touché.


Thanks for the python code.

**Comment by tejaswigowda** [comment]
Got it to work. Thank you so much!!
